In [ ]:
import numpy as np

Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [ ]:
np.random.seed(3)

a = np.random.randint(1,5, (8,3))
b = np.random.randint(1,3, (2,2))

print(a, set(b.flatten()), sep='\n')

for x in a:
    if set(x).intersection(set(b.flatten())) == set(b.flatten()):
        print(x)

[[3 1 2]
 [4 1 1]
 [1 2 2]
 [4 3 4]
 [2 2 3]
 [2 4 3]
 [1 1 1]
 [2 4 3]]
{np.int64(1), np.int64(2)}
[3 1 2]
[1 2 2]


Создайте массив из 1000 элементов со случайными значениями в диапазоне от [1, 10000]. Вывести n наибольших значений в массиве.

In [ ]:
np.random.seed(3)

n = int(input('введите число наибольших чисел: '))

a = np.random.randint(1, 10000, 1000)

print(np.sort(a)[:len(a) - n:-1])

введите число наибольших чисел: 9
[9996 9982 9981 9958 9952 9952 9937 9911]


Создайте матрицу (90х76) со случайными значениями в диапазоне от [1, 10000]. Посчитайте ранг матрицы.

In [ ]:
np.random.seed(3)

a = np.random.randint(1, 10000, (90,76))

print(np.linalg.matrix_rank(a))

76


Используя модуль linalg выполните расчеты над автоматически генерируемой вектором/матрицей:

* решите систему линейных уравнений Ax = b;
* посчитать определитель матрицы;
* определить норму вектора;
* возведите матрицу в степень n;
* выведите обратную матрицу.

In [ ]:
# система лин. уравнений

a = [[6,3], [3,-4]]
b = [1,2]

print(np.linalg.solve(a, b))

[ 0.3030303  -0.27272727]


In [ ]:
np.random.seed(3)

# определитель матрицы

matrix = np.random.randint(1, 10, (5,5))

print(f'{matrix} \n {np.linalg.det(matrix)}')

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]
 [7 3 3 2 4]
 [6 9 2 9 8]] 
 8219.999999999998


In [ ]:
np.random.seed(3)

# норма вектора

vector = np.random.randint(1, 100, 5)
print(vector, np.linalg.vector_norm(vector), sep='\n')

[25  4 57 73  1]
96.02083107326243


In [ ]:
np.random.seed(3)

# возведение матрицы в степень n

n = int(input('введите степень: '))

matrix = np.random.randint(1, 100, (5,5))

print(f'{matrix} \n {np.linalg.matrix_power(matrix, n)}')

введите степень: 2
[[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 97 21 45]
 [94 40 15 27 82]
 [91 23 67  3 64]] 
 [[ 8920  5346  8416  5164  8684]
 [ 7589  5346 11396  5188  7765]
 [ 9611  6526 16918  5983  9418]
 [13560  4727 15712  9832  8671]
 [10361  5029 17744  9289  7701]]


In [ ]:
np.random.seed(3)

# обратная матрица

matrix = np.random.randint(1, 100, (5,5))
print(f'{matrix} \n {np.linalg.inv(matrix)}')

[[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 97 21 45]
 [94 40 15 27 82]
 [91 23 67  3 64]] 
 [[-0.01844887  0.04379029 -0.02960329  0.0038225   0.00867904]
 [-0.05831416  0.10269088 -0.030407    0.02455237 -0.02681664]
 [ 0.00367454 -0.00399889  0.00683168 -0.00998575  0.00862061]
 [ 0.01976184 -0.01621043  0.00584535  0.00519814 -0.00829274]
 [ 0.04241552 -0.09422265  0.04559378 -0.00404846  0.00428574]]
